-- Helena Task Manager — Beta
-- Migration: Saúde / Leitor de treinos (workouts + workout_sets)
--
-- Idempotente: pode ser executado várias vezes sem erro nem duplicação.
-- Não altera nem remove nenhuma tabela existente de tarefas, hábitos ou
-- financeiro.

create table if not exists workouts (
    id           bigint generated by default as identity primary key,
    workout_date date not null,
    name         text not null,
    source       text,
    source_url   text,
    created_at   timestamptz not null default now()
);

create table if not exists workout_sets (
    id                bigint generated by default as identity primary key,
    workout_id        bigint not null references workouts(id) on delete cascade,
    exercise_name     text not null,
    exercise_order    integer not null,
    set_number        integer not null,
    repetitions       integer,
    weight            numeric,
    duration_seconds  integer,
    unit              text,
    notes             text,
    set_type          text,
    created_at        timestamptz not null default now(),
    constraint workout_sets_repetitions_check check (repetitions is null or repetitions >= 0),
    constraint workout_sets_weight_check check (weight is null or weight >= 0),
    constraint workout_sets_duration_check check (duration_seconds is null or duration_seconds >= 0)
);

create index if not exists idx_workouts_workout_date on workouts (workout_date);
create index if not exists idx_workout_sets_workout_id on workout_sets (workout_id);
create index if not exists idx_workout_sets_exercise_name on workout_sets (exercise_name);

-- Persistência transacional (workout + suas séries em uma única operação
-- atômica): se qualquer inserção falhar, a função inteira é desfeita e
-- nenhum treino fica parcialmente salvo (ver app/workouts/service.py).
create or replace function create_workout_with_sets(payload jsonb)
returns jsonb
language plpgsql
as $$
declare
    new_workout_id bigint;
    ex jsonb;
    st jsonb;
begin
    insert into workouts (workout_date, name, source, source_url)
    values (
        (payload->>'workout_date')::date,
        payload->>'name',
        payload->>'source',
        payload->>'source_url'
    )
    returning id into new_workout_id;

    for ex in select * from jsonb_array_elements(payload->'exercises')
    loop
        for st in select * from jsonb_array_elements(ex->'sets')
        loop
            insert into workout_sets (
                workout_id, exercise_name, exercise_order, set_number,
                repetitions, weight, duration_seconds, unit, notes, set_type
            ) values (
                new_workout_id,
                ex->>'exercise_name',
                (ex->>'exercise_order')::int,
                (st->>'set_number')::int,
                nullif(st->>'repetitions', '')::int,
                nullif(st->>'weight', '')::numeric,
                nullif(st->>'duration_seconds', '')::int,
                nullif(st->>'unit', ''),
                nullif(st->>'notes', ''),
                nullif(ex->>'set_type', '')
            );
        end loop;
    end loop;

    return jsonb_build_object('id', new_workout_id);
end;
$$;
